### ISSUE TITLE
Ajustar layout da tela de sign in e sign up

### ISSUE THREAD

**Issue by senott** [OBC-HCKTON-GRP03/OneBitHealth#7]
Segue os modelos base feito pelo @JorgeLAB no figma.

Tela de cadastro:
![image](https://user-images.githubusercontent.com/62290004/101669022-1cbe3200-3a30-11eb-8ec4-f06afef5819b.png)

Tela de login:
![image](https://user-images.githubusercontent.com/62290004/101669052-26479a00-3a30-11eb-8f08-24aac8c5c5b0.png)

**Comment by JorgeLAB** [comment]
The implementation of the styles was carried out. It has an observation regarding the route of sign_in email and the location of the error launch in sign_up.
